
const parametersType = {
    FETCH_ENERGY_CONSUMPTION_LOADING: 'FETCH_ENERGY_CONSUMPTION_LOADING',
    FETCH_ENERGY_CONSUMPTION_SUCCESS: 'FETCH_ENERGY_CONSUMPTION_SUCCESS',

    FETCH_POWER_QUALITY_LOADING: 'FETCH_POWER_QUALITY_LOADING',
    FETCH_POWER_QUALITY_SUCCESS: 'FETCH_POWER_QUALITY_SUCCESS',

    FETCH_POWER_DEMAND_LOADING: 'FETCH_POWER_DEMAND_LOADING',
    FETCH_POWER_DEMAND_SUCCESS: 'FETCH_POWER_DEMAND_SUCCESS',
    
    FETCH_LAST_READING_LOADING: 'FETCH_LAST_READING_LOADING',
    FETCH_LAST_READING_SUCCESS: 'FETCH_LAST_READING_SUCCESS',
}

export default parametersType;