const alertsAndAlarmTypes = {
    GET_ALERTS_AND_ALARM_LOADING: 'GET_ALERTS_AND_ALARM_LOADING',
    GET_ALERTS_AND_ALARM_SUCCESS: 'GET_ALERTS_AND_ALARM_SUCCESS',
    
    SET_ALERTS_AND_ALARM_LOADING: 'SET_ALERTS_AND_ALARM_LOADING',
    SET_ALERTS_AND_ALARM_SUCCESS: 'SET_ALERTS_AND_ALARM_SUCCESS',
}

export default alertsAndAlarmTypes;