
const scoreCardType = {
    FETCH_SCORECARD_LOADING: 'FETCH_SCORECARD_LOADING',
    FETCH_SCORECARD_SUCCESS: 'FETCH_SCORECARD_SUCCESS',
    FETCH_SCORECARD_UI_LOADING: 'FETCH_SCORECARD_UI_LOADING',
    FETCH_SCORECARD_UI_SUCCESS: 'FETCH_SCORECARD_UI_SUCCESS',
    GET_BASELINE_ENERGY_LOADING: 'GET_BASELINE_ENERGY_LOADING',
    GET_BASELINE_ENERGY_SUCCESS: 'GET_BASELINE_ENERGY_SUCCESS',
    GET_PAPR_LOADING: 'GET_PAPR_LOADING',
    GET_PAPR_SUCCESS: 'GET_PAPR_SUCCESS',
    GET_SCORECARD_CARBON_EMISSION_LOADING: 'GET_SCORECARD_CARBON_EMISSION_LOADING',
    GET_SCORECARD_CARBON_EMISSION_SUCCESS: 'GET_SCORECARD_CARBON_EMISSION_SUCCESS',
    GET_GENERATOR_SIZE_EFFICIENCY_LOADING: 'GET_GENERATOR_SIZE_EFFICIENCY_LOADING',
    GET_GENERATOR_SIZE_EFFICIENCY_SUCCESS: 'GET_GENERATOR_SIZE_EFFICIENCY_SUCCESS',
    GET_GENERATOR_FUEL_EFFICIENCY_LOADING: 'GET_GENERATOR_FUEL_EFFICIENCY_LOADING',
    GET_GENERATOR_FUEL_EFFICIENCY_SUCCESS: 'GET_GENERATOR_FUEL_EFFICIENCY_SUCCESS',
    GET_OPERATING_TIME_DEVIATION_LOADING: 'GET_OPERATING_TIME_DEVIATION_LOADING',
    GET_OPERATING_TIME_DEVIATION_SUCCESS: 'GET_OPERATING_TIME_DEVIATION_SUCCESS',
}

export default scoreCardType;