
const authTypes = {
    LOGOUT_USER: 'LOGOUT_USER',

    GET_PERMITTED_BRANCHES_LOADING: 'GET_PERMITTED_BRANCHES_LOADING',
    GET_PERMITTED_BRANCHES_SUCCESS: 'GET_PERMITTED_BRANCHES_SUCCESS',
    
    SWITCH_BRANCH_LOADING: 'SWITCH_BRANCH_LOADING',
    SWITCH_BRANCH_SUCCESS: 'SWITCH_BRANCH_SUCCESS',
}

export default authTypes;