
const authTypes = {
    LOGOUT_USER: 'LOGOUT_USER',

    RESET_PASSWORD_LOADING: 'RESET_PASSWORD_LOADING',
    RESET_PASSWORD_SUCCESS: 'RESET_PASSWORD_SUCCESS',

    CONFIRM_RESET_PASSWORD_LOADING: 'CONFIRM_RESET_PASSWORD_LOADING',
    CONFIRM_RESET_PASSWORD_SUCCESS: 'CONFIRM_RESET_PASSWORD_SUCCESS',

    VALIDATE_RESET_TOKEN_LOADING: 'VALIDATE_RESET_TOKEN_LOADING',
    VALIDATE_RESET_TOKEN_SUCCESS: 'VALIDATE_RESET_TOKEN_SUCCESS',

    GET_PERMITTED_BRANCHES_LOADING: 'GET_PERMITTED_BRANCHES_LOADING',
    GET_PERMITTED_BRANCHES_SUCCESS: 'GET_PERMITTED_BRANCHES_SUCCESS',

    SWITCH_BRANCH_LOADING: 'SWITCH_BRANCH_LOADING',
    SWITCH_BRANCH_SUCCESS: 'SWITCH_BRANCH_SUCCESS',
}

export default authTypes;