const dieselType = {
    FETCH_GENERATORS_STATUS_LOADING: 'FETCH_GENERATORS_STATUS_LOADING',
    FETCH_GENERATORS_STATUS_SUCCESS: 'FETCH_GENERATORS_STATUS_SUCCESS',

    FETCH_GENERATOR_MONTHLY_ENERGY_LOADING: 'FETCH_GENERATOR_MONTHLY_ENERGY_LOADING',
    FETCH_GENERATOR_MONTHLY_ENERGY_SUCCESS: 'FETCH_GENERATOR_MONTHLY_ENERGY_SUCCESS',

    FETCH_DIESEL_PRICE_LOADING: 'FETCH_DIESEL_PRICE_LOADING',
    FETCH_DIESEL_PRICE_SUCCESS: 'FETCH_DIESEL_PRICE_SUCCESS',
}

export default dieselType;