const dieselType = {
    FETCH_GENERATORS_STATUS_LOADING: 'FETCH_GENERATORS_STATUS_LOADING',
    FETCH_GENERATORS_STATUS_SUCCESS: 'FETCH_GENERATORS_STATUS_SUCCESS',

    FETCH_CO2_EMISSION_LOADING: 'FETCH_CO2_EMISSION_LOADING',
    FETCH_CO2_EMISSION_SUCCESS: 'FETCH_CO2_EMISSION_SUCCESS',
    
    FETCH_DIESEL_PRICE_LOADING: 'FETCH_DIESEL_PRICE_LOADING',
    FETCH_DIESEL_PRICE_SUCCESS: 'FETCH_DIESEL_PRICE_SUCCESS',

    FETCH_GENERATOR_MONTHLY_ENERGY_LOADING: 'FETCH_GENERATOR_MONTHLY_ENERGY_LOADING',
    FETCH_GENERATOR_MONTHLY_ENERGY_SUCCESS: 'FETCH_GENERATOR_MONTHLY_ENERGY_SUCCESS',

    FETCH_GEN_STATUS_CHART_LOADING: 'FETCH_GEN_STATUS_CHART_LOADING',
    FETCH_GEN_STATUS_CHART_SUCCESS: 'FETCH_GEN_STATUS_CHART_SUCCESS',

    FETCH_GEN_FUEL_USAGE_LOADING: 'FETCH_GEN_FUEL_USAGE_LOADING',
    FETCH_GEN_FUEL_USAGE_SUCCESS: 'FETCH_GEN_FUEL_USAGE_SUCCESS',

    FETCH_FUEL_USAGE_LOADING: 'FETCH_FUEL_USAGE_LOADING',
    FETCH_FUEL_USAGE_SUCCESS: 'FETCH_FUEL_USAGE_SUCCESS',

    FETCH_OPERATIONAL_EFFICIENCY_LOADING: 'FETCH_OPERATIONAL_EFFICIENCY_LOADING',
    FETCH_OPERATIONAL_EFFICIENCY_SUCCESS: 'FETCH_OPERATIONAL_EFFICIENCY_SUCCESS',
    
    FETCH_COST_ANALYSIS_LOADING: 'FETCH_COST_ANALYSIS_LOADING',
    FETCH_COST_ANALYSIS_SUCCESS: 'FETCH_COST_ANALYSIS_SUCCESS',
}

export default dieselType;