const solarType = {
    FETCH_WEATHER_READINGS_LOADING: 'FETCH_WEATHER_READINGS_LOADING',
    FETCH_WEATHER_READINGS_SUCCESS: 'FETCH_WEATHER_READINGS_SUCCESS',

    FETCH_COMPONENTS_TABLE_LOADING: 'FETCH_COMPONENTS_TABLE_LOADING',
    FETCH_COMPONENTS_TABLE_SUCCESS: 'FETCH_COMPONENTS_TABLE_SUCCESS',

    FETCH_INVERTER_ANIMATION_LOADING: 'FETCH_INVERTER_ANIMATION_LOADING',
    FETCH_INVERTER_ANIMATION_SUCCESS: 'FETCH_INVERTER_ANIMATION_SUCCESS',

    FETCH_CONSUMPTION_CHART_LOADING: 'FETCH_CONSUMPTION_CHART_LOADING',
    FETCH_CONSUMPTION_CHART_SUCCESS: 'FETCH_CONSUMPTION_CHART_SUCCESS',
}

export default solarType;