const solarType = {
    FETCH_WEATHER_READINGS_LOADING: 'FETCH_WEATHER_READINGS_LOADING',
    FETCH_WEATHER_READINGS_SUCCESS: 'FETCH_WEATHER_READINGS_SUCCESS',

    FETCH_COMPONENTS_TABLE_LOADING: 'FETCH_COMPONENTS_TABLE_LOADING',
    FETCH_COMPONENTS_TABLE_SUCCESS: 'FETCH_COMPONENTS_TABLE_SUCCESS',

    FETCH_INVERTER_GRIDS_LOADING: 'FETCH_INVERTER_GRIDS_LOADING',
    FETCH_INVERTER_GRIDS_SUCCESS: 'FETCH_INVERTER_GRIDS_SUCCESS',

    FETCH_CONSUMPTION_CHART_LOADING: 'FETCH_CONSUMPTION_CHART_LOADING',
    FETCH_CONSUMPTION_CHART_SUCCESS: 'FETCH_CONSUMPTION_CHART_SUCCESS',

    FETCH_PV_PRODUCTION_CHART_LOADING: 'FETCH_PV_PRODUCTION_CHART_LOADING',
    FETCH_PV_PRODUCTION_CHART_SUCCESS: 'FETCH_PV_PRODUCTION_CHART_SUCCESS',

    FETCH_BATTERY_CHART_LOADING: 'FETCH_BATTERY_CHART_LOADING',
    FETCH_BATTERY_CHART_SUCCESS: 'FETCH_BATTERY_CHART_SUCCESS',
}

export default solarType;